services:
  adguardhome:
    image: docker.io/adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    volumes:
      - ./data/adguard-config/:/opt/adguardhome/conf/
      - ./data/adguard-data/:/opt/adguardhome/work/
    ports:
      # Plain DNS
      - "53:53/tcp"
      - "53:53/udp"
      # Admin panel
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
      - "3000:3000/tcp"
      # DNS-over-TLS
      - "853:853/tcp"

  tor:
    build:
      context: .
      dockerfile: Dockerfile.tor
    container_name: tor
    restart: unless-stopped
    volumes:
      - ./torrc:/etc/tor/torrc
    ports:
      # SOCKS5 proxy
      - "9050:9050/tcp"

  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:13
    container_name: wg-easy
    restart: unless-stopped
    depends_on:
      - adguardhome
      - tor
    volumes:
      - ./data/wg-easy/:/etc/wireguard/
    ports:
      # WireGuard VPN port
      - "51820:51820/udp"
      # Admin panel
      - "51821:51821/tcp"
    environment:
      - WG_HOST=home.efima.ru
      - PASSWORD=${PASSWORD}
      - WG_DEFAULT_ADDRESS=192.168.100.x
      - WG_DEFAULT_DNS=192.168.0.30
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
