FROM alpine

RUN apk -U upgrade && \
    apk -v add tor lyrebird && \
    chmod 700 /var/lib/tor && \
    rm -rf /var/cache/apk/*

USER tor
EXPOSE 9150/tcp

CMD ["/usr/bin/tor", "-f", "/etc/tor/torrc"]
