FROM alpine:edge

RUN apk -U upgrade && \
    apk -v add tor lyrebird && \
    chmod 700 /var/lib/tor && \
    rm -rf /var/cache/apk/*

HEALTHCHECK --timeout=10s --start-period=60s \
  CMD curl -fIL --socks5-hostname localhost:9050 'https://www.facebookwkhpilnemxj7asaniu7vnjjbiltxjqhye3mhbshg7kx5tfyd.onion/' || exit 1

USER tor
EXPOSE 9050/tcp

CMD ["/usr/bin/tor", "-f", "/etc/tor/torrc"]
